services:
  - type: web
    name: resonance-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:10000 app:app
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache
